name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.5
    - name: Install dependencies listed in Project.toml and build package
      uses: julia-actions/julia-buildpkg@master
    - run: julia --project -e '
            using Pkg; Pkg.develop([PackageSpec(name="Franklin", rev="rssfix"), PackageSpec(name="FranklinTemplates", rev="rssfix")]);
            using Franklin;
            optimize(minify=false, prerender=false);'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: __site
